config/routes.rb
Rails.application.routes.draw do

  #ROOT

  root to: 'pages#home'

  #DEVISE

  devise_for :users

  #BURGER PLACES

  resources :burger_places, only: [:index]
  get "hamburguerias/:display_name", to: "burger_places#show", as: "hamburgeria"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/burger_place.rb
class BurgerPlace < ApplicationRecord
  before_save :set_display_name
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def set_display_name
    self.display_name = ("#{self.name.downcase} #{self.address.downcase}").gsub(/[^0-9A-Za-z ]/, '').split(" ").join("-")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/burger_places_controller.rb
class BurgerPlacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @burger_places = BurgerPlace.where.not(latitude: nil, longitude: nil)

    @markers = @burger_places.map do |burger_place|
      {
        lng: burger_place.longitude,
        lat: burger_place.latitude,
        infoWindow: { content: render_to_string(partial: "/burger_places/map_window", locals: { burger_place: burger_place }) }
      }
    end
  end

  def show
    @burger_place = BurgerPlace.find_by(display_name: params[:display_name])
    @marker = [{ lng: @burger_place.longitude, lat: @burger_place.latitude,
        infoWindow: { content: render_to_string(partial: "/burger_places/show_map_window", locals: { burger_place: @burger_place }) } }]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @burger_places = BurgerPlace.where.not(latitude: nil, longitude: nil)

    @markers = @burger_places.map do |burger_place|
      {
        lng: burger_place.longitude,
        lat: burger_place.latitude,
        infoWindow: { content: render_to_string(partial: "/burger_places/map_window", locals: { burger_place: burger_place }) }
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/burger_places/_map_window.html.erb
<%= link_to hamburgeria_path(display_name: burger_place.display_name) do %>
  <div class="row">
    <div class="col-xs-6">
      <h3><%= burger_place.name %></h3>
      <p><%= burger_place.address %></p>
    </div>
      <div class="col-xs-6">
      <%= image_tag "display-burger.jpg", class: "display-img" %>
    </div>
  </div>
<% end %>

app/views/burger_places/_show_map_window.html.erb
hello

app/views/burger_places/index.html.erb
<h1>BurgerPlaces#index</h1>
<p>Find me in app/views/burger_places/index.html.erb</p>

app/views/burger_places/show.html.erb
<div class="row">
  <div class="col-xs-8">
    <div class="burger-place-info">
      <h1><%= @burger_place.name %></h1>
      <h2><%= @burger_place.address%></h2>
      <% @burger_place.rating.to_i.times do %> <i class="fas fa-star" style="color: orange"></i> <% end %>
      <h4> R$ <%= @burger_place.price %></h4>
      <% if @burger_place.price < 35 %>
       <h4> Esse é o hamburger mais barato perto de você !</h4>
       <% end %>
     </div>
   </div>
   <div class="col-xs-4">
    <div
      id="map"
      style="width: 100%;
      height: 100vh;"
      data-markers="<%= @marker.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="<%= image_path 'geoburger.png' %>">
    <title>GeoBurger</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="burger-banner" style="background-image:  url(<%= asset_path 'burgers-banner.png' %>)">
  <div class="banner-content">
    <h1>GeoBurger</h1>
    <p>Descubra hambúrgeres saborosos perto de você</p>
    <a href="#" class="scroll-down">↓</a>
  </div>
</div>
<div
  id="map"
  style="width: 100%;
  height: 80vh;
  border-bottom: 1px solid black"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
<div class="container home-list">
  <div class="row">
    <div class="col-xs-6">
      <h2 class="text-center list-title">GeoBurger</h2>
      <ul style="list-style: none;">
        <li><i class="fas fa-map-marker-alt"></i> Encontre o hambúrguer mais perto de você</li>
        <li><i class="far fa-star"></i> Avalie suas hamburguerias preferidas</li>
        <li><i class="far fa-comment"></i> Deixe seu review  </li>
        <li><i class="fas fa-users"></i> Seja parte da comunidade louca por hambúrgueres</li>
      </ul>
    </div>
    <div class="col-xs-6">
      <%= image_tag "girl.jpg", class: "girl-image" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="<%= current_page?('/') ? 'navbar-root' : 'navbar-show' %>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "blackburger.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>